# Generated by Django 5.2.1 on 2026-06-05 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('customer', 'مشتری'), ('colleague', 'همکار'), ('wholesaler', 'بنکدار'), ('melted_gold_seller', 'آبشده فروش'), ('gold_bank', 'بانک طلا')], max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('national_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت'), ('cheque', 'چک')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveBigIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChequePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('account_owner', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cheques/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_detail', to='transactions.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=30)),
                ('terminal_number', models.CharField(blank=True, max_length=50)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_detail', to='transactions.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gold_category', models.CharField(choices=[('melted', 'طلای آبشده'), ('normal', 'طلای عادی')], max_length=20)),
                ('normal_gold_type', models.CharField(blank=True, choices=[('manufactured', 'طلای ساخته'), ('misc', 'طلای متفرقه')], max_length=20)),
                ('gold_status', models.CharField(choices=[('pending', 'در انتظار'), ('delivered', 'تحویل شده')], default='pending', max_length=20)),
                ('gold_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.branch')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.counterparty')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.transaction'),
        ),
        migrations.CreateModel(
            name='MiscGoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('karat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misc_gold', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='MeltedGoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('assay', models.DecimalField(decimal_places=3, max_digits=8)),
                ('melting_code', models.CharField(blank=True, max_length=100)),
                ('package_number', models.CharField(blank=True, max_length=100)),
                ('laboratory_number', models.CharField(blank=True, max_length=100)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='melted_gold', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturedGoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('karat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('wage', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_gold', to='transactions.transaction')),
            ],
        ),
    ]
