# Generated by Django 5.2.1 on 2026-06-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('national_code', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('customer', 'مشتری'), ('colleague', 'همکار'), ('wholesaler', 'بنکدار'), ('melted_gold_seller', 'آبشده فروش'), ('gold_bank', 'بانک طلا')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('gold_status', models.CharField(choices=[('pending', 'در انتظار'), ('delivered', 'تحویل شده')], default='pending', max_length=20)),
                ('gold_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.branch')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.counterparty')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت'), ('cheque', 'چک')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='panel.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('melted', 'طلای آبشده'), ('normal', 'طلای عادی')], max_length=20)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold', to='panel.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='NormalGoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_type', models.CharField(choices=[('manufactured', 'طلای ساخته'), ('misc', 'متفرقه')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('karat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gold', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_detail', to='panel.transactiongold')),
            ],
        ),
        migrations.CreateModel(
            name='MeltedGoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('assay', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gold', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='melted_detail', to='panel.transactiongold')),
            ],
        ),
    ]
